import {FIELDS,BASIC_FIELDS,DATE_FIELDS,validateYear,statusOf,filtered,copyForYear,keyOf,tieKey} from './model.js';
import {INITIAL_2026,NOTES} from './default-data.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cloud,owner=false,config=null,configVersion=0,current=null,yearVersion=0,unsubCfg,unsubYear,busy=false,pendingImport=null,editingId=null,printRows=null;
const unique=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'zh-Hant'));
const currentYear=()=>Number($('year').value||current?.year||2026);
const filters=()=>({company:$('f-company').value,division:$('f-division').value,site:$('f-site').value,plant:$('f-plant').value,type:$('f-type').value,status:$('f-status').value,query:$('f-query').value});
const visible=()=>current?filtered(current.rows,filters(),current.year):[];
function msg(t){$('sync').textContent=t;}
function disabled(v){for(const id of ['new-year','archive','import','export','print','add','reset'])$(id).disabled=v;}
function option(v){return `<option value="${esc(v)}">${esc(v)}</option>`;}
function fillSelect(id,values,all='全部'){const el=$(id),old=el.value;el.innerHTML=`<option value="">${all}</option>`+values.map(option).join('');el.value=values.includes(old)?old:'';}
function fillFilters(){if(!current)return;fillSelect('f-company',unique(current.rows.map(r=>r.company)));fillSelect('f-division',unique(current.rows.filter(r=>!$('f-company').value||r.company===$('f-company').value).map(r=>r.division)));fillSelect('f-site',unique(current.rows.map(r=>r.site)));fillSelect('f-plant',unique(current.rows.filter(r=>!$('f-site').value||r.site===$('f-site').value).map(r=>r.plant)));fillSelect('f-type',unique(current.rows.map(r=>r.inspectionType)));}
function render(){
 $('app').hidden=!owner||!current;$('gate').hidden=owner&&!!current;if(!owner||!current)return;
 fillFilters();const rows=visible(),arch=!!current.archived;$('archive-badge').hidden=!arch;$('archive').textContent=arch?'解除封存':'封存年度';$('add').disabled=arch||busy;$('import').disabled=arch||busy;$('count').textContent=`顯示 ${rows.length} / ${current.rows.length} 筆`;
 $('empty').hidden=rows.length>0;$('tbody').innerHTML=rows.map((r,i)=>{const s=statusOf(r,current.year);return `<tr><td>${i+1}</td><td><span class="status ${s.status}" title="${esc(s.reason)}">${s.status}</span></td>${FIELDS.map(([k])=>`<td>${esc(r[k])||'—'}</td>`).join('')}<td class="row-actions"><button data-edit="${r.id}" ${arch?'disabled':''}>編輯</button><button class="danger" data-delete="${r.id}" ${arch?'disabled':''}>刪除</button></td></tr>`}).join('');disabled(busy);
 $('add').disabled=arch||busy;$('import').disabled=arch||busy;
}
$('thead').innerHTML='<tr><th>項次</th><th>狀態</th>'+FIELDS.map(([,h])=>`<th>${esc(h)}</th>`).join('')+'<th>操作</th></tr>';
$('notes').innerHTML=NOTES.map(n=>`<li>${esc(n)}</li>`).join('');
$('form-grid').innerHTML=FIELDS.map(([k,h])=>`<label>${esc(h)}${['company','site','plant','unitName','inspectionType'].includes(k)?' *':''}<input name="${k}" maxlength="120" ${['company','site','plant','unitName','inspectionType'].includes(k)?'required':''} placeholder="${DATE_FIELDS.includes(k)?'YYYY-MM-DD、(MM/DD) 或 -':''}"></label>`).join('');
for(const id of ['f-company','f-division','f-site','f-plant','f-type','f-status'])$(id).addEventListener('change',render);$('f-query').addEventListener('input',render);$('reset').onclick=()=>{for(const id of ['f-company','f-division','f-site','f-plant','f-type','f-status','f-query'])$(id).value='';render();};
function confirmBox(title,text){return new Promise(resolve=>{const d=$('confirm-dialog');$('confirm-title').textContent=title;$('confirm-text').textContent=text;d.returnValue='cancel';d.addEventListener('close',()=>resolve(d.returnValue==='confirm'),{once:true});d.showModal();});}
async function persist(next){if(!owner||busy||current.archived)throw Error('目前年度已封存或尚未登入。');busy=true;render();msg('儲存中…');const expected=yearVersion;try{validateYear(next);await cloud.saveYear(next,expected);if(yearVersion<=expected){current=next;yearVersion=expected+1;}msg('已同步');}finally{busy=false;render();}}
function openEdit(id){if(current.archived)return;editingId=id||null;const row=id?current.rows.find(x=>x.id===id):Object.fromEntries(FIELDS.map(([k])=>[k,'']));const f=$('edit-form');f.reset();for(const [k] of FIELDS)f.elements[k].value=row?.[k]||'';$('edit-title').textContent=id?'編輯資料':'新增資料';$('edit-dialog').showModal();}
$('add').onclick=()=>openEdit();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('edit-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const row={id:editingId||crypto.randomUUID()};for(const [k] of FIELDS)row[k]=e.target.elements[k].value.trim();const next=structuredClone(current);const at=next.rows.findIndex(x=>x.id===row.id);if(at>=0)next.rows[at]=row;else next.rows.push(row);try{await persist(next);$('edit-dialog').close();editingId=null;}catch(err){alert(err.message);}};
$('tbody').onclick=async e=>{const eb=e.target.closest('[data-edit]'),db=e.target.closest('[data-delete]');if(eb)return openEdit(eb.dataset.edit);if(db&&!busy&&!current.archived){const r=current.rows.find(x=>x.id===db.dataset.delete);if(!r)return;if(await confirmBox('刪除資料',`確定刪除「${r.site}／${r.plant}／${r.unitName}」？`)){const next=structuredClone(current);next.rows=next.rows.filter(x=>x.id!==r.id);try{await persist(next);}catch(err){alert(err.message);}}}};
function excelValue(v){const s=String(v??'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d);}return s;}
const TOP=['項次','公司','事業部','廠區','廠處','地址','定檢(工檢)    單元名稱','定檢(工檢)              類型','停俥開始     日期','停俥結束        日期','函報主管機關定檢日期','','定檢前         教育訓練','局限作業                           災害防止計劃','', '職災防止 檢討會議          日期','定檢聯檢                       開始日期','定檢聯檢                       結束日期','啟動前安全檢查(PSSR)','', '開俥           日期','FTIR監測報告','定檢聯檢     報告','承攬商輔導            交流會日期'];
const SUB=['','','','','','','','','','','定檢(工檢)           前一個月','定檢(工檢)完成','','檢討修訂           日期','演練日期','','','','起始會議          日期','審查會議            日期','','','',''];
function makeWorkbook(rows,year){if(!window.XLSX)throw Error('Excel 元件尚未載入。');const aoa=[[null,`${year}年台化公司生產廠定檢(工檢)工安業務執行表`,...Array(22).fill(null)],TOP,SUB];rows.forEach((r,i)=>aoa.push([i+1,...FIELDS.map(([k])=>excelValue(r[k]))]));aoa.push([]);NOTES.forEach(n=>aoa.push(['',n]));const ws=XLSX.utils.aoa_to_sheet(aoa,{cellDates:true});ws['!merges']=[XLSX.utils.decode_range('B1:X1'),XLSX.utils.decode_range('K2:L2'),XLSX.utils.decode_range('N2:O2'),XLSX.utils.decode_range('S2:T2')];ws['!cols']=Array.from({length:24},(_,i)=>({wch:[6,10,11,10,14,28,18,14,15,15,18,18,16,18,14,17,17,17,17,17,14,16,16,18][i]}));for(const c of Object.keys(ws)){if(c[0]==='!')continue;const cell=ws[c];if(cell.v instanceof Date){cell.z='yyyy/mm/dd';}}const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'定檢工檢工安業務');return wb;}
$('export').onclick=()=>{try{XLSX.writeFile(makeWorkbook(current.rows,current.year),`${current.year}年台化公司生產廠定檢(工檢)工安業務執行表.xlsx`);}catch(e){alert(e.message);}};
function cellString(v){if(v==null)return'';if(v instanceof Date){const y=v.getFullYear(),m=String(v.getMonth()+1).padStart(2,'0'),d=String(v.getDate()).padStart(2,'0');return`${y}-${m}-${d}`;}if(typeof v==='number'){const p=XLSX.SSF.parse_date_code(v);if(p&&p.y>=2000&&p.y<=2200)return`${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`;}return String(v).trim();}
function readImport(file){return file.arrayBuffer().then(buf=>{const wb=XLSX.read(buf,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],a=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:''});const title=String(a?.[0]?.[1]||'');if(!title.includes('定檢(工檢)工安業務執行表'))throw Error('不是本系統匯出的定檢（工檢）標準範本。');const year=Number((title.match(/(20\d{2})年/)||[])[1]);if(year!==current.year)throw Error(`Excel 年度為 ${year||'無法辨識'}，目前系統年度為 ${current.year}。`);const rows=[],carry={company:'',division:'',site:'',plant:'',address:''};for(let i=3;i<a.length;i++){const x=a[i]||[],b=x.slice(1,24).map(cellString);if(!b[5]||!b[6])continue;if(b[0])carry.company=b[0];if(b[1])carry.division=b[1];if(b[2])carry.site=b[2];if(b[3]){carry.plant=b[3];carry.address=b[4]||'';}else if(b[4])carry.address=b[4];const r={id:crypto.randomUUID(),company:carry.company,division:carry.division,site:carry.site,plant:carry.plant,address:carry.address};FIELDS.slice(5).forEach(([k],j)=>r[k]=b[j+5]||'');rows.push(r);}if(!rows.length)throw Error('Excel 中找不到可匯入資料。');return rows;});}
function reconcile(imported){const existing=current.rows;const primary=new Map(),tie=new Map();for(const r of existing){const k=keyOf(current.year,r);primary.set(k,[...(primary.get(k)||[]),r]);tie.set(tieKey(current.year,r),r);}const used=new Set(),updated=[],added=[];for(const r of imported){const k=keyOf(current.year,r),cands=primary.get(k)||[];let match;if(cands.length===1)match=cands[0];else if(cands.length>1)match=tie.get(tieKey(current.year,r));if(match&&!used.has(match.id)){updated.push({...r,id:match.id});used.add(match.id);}else added.push(r);}const missing=existing.filter(r=>!used.has(r.id));return{updated,added,missing};}
$('import').onclick=()=>{if(!current.archived)$('file').click();};$('file').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const rows=await readImport(file);pendingImport=reconcile(rows);$('import-summary').textContent=`比對結果：更新 ${pendingImport.updated.length} 筆、新資料 ${pendingImport.added.length} 筆、Excel 缺少系統既有資料 ${pendingImport.missing.length} 筆。`;$('import-add').checked=false;$('import-delete').checked=false;$('import-dialog').showModal();}catch(err){alert(err.message);}};
$('import-dialog').addEventListener('close',async()=>{if($('import-dialog').returnValue!=='confirm'||!pendingImport)return;const p=pendingImport;pendingImport=null;const next=structuredClone(current),map=new Map(p.updated.map(r=>[r.id,r]));next.rows=next.rows.map(r=>map.get(r.id)||r);if($('import-add').checked)next.rows.push(...p.added);if($('import-delete').checked){const miss=new Set(p.missing.map(r=>r.id));next.rows=next.rows.filter(r=>!miss.has(r.id));}try{await persist(next);}catch(err){alert(err.message);}});
$('print').onclick=()=>{$('print-dialog').showModal();};$('print-dialog').addEventListener('close',()=>{if($('print-dialog').returnValue!=='confirm')return;const scope=document.querySelector('#print-dialog [name=scope]:checked').value;printRows=scope==='all'?current.rows:visible();renderPrint(printRows);setTimeout(()=>window.print(),50);});
function renderPrint(rows){$('print-root').innerHTML=`<div class="print-sheet"><h1>${current.year}年台化公司生產廠定檢(工檢)工安業務執行表</h1><table><thead><tr><th>項次</th>${FIELDS.map(([,h])=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td>${FIELDS.map(([k])=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table><ol class="print-notes">${NOTES.map(n=>`<li>${esc(n)}</li>`).join('')}</ol></div>`;}
$('new-year').onclick=async()=>{if(busy||!current)return;const y=Number(prompt('請輸入新年度，例如 2027：',String(current.year+1)));if(!Number.isInteger(y)||y<2000||y>2200)return;if(config.years.some(x=>x.year===y)){alert('此年度已存在。');return;}if(!await confirmBox('建立新年度',`建立 ${y} 年度，並複製 ${current.year} 年的基本資料；所有日期與執行情況將清空。`))return;busy=true;render();try{const next=copyForYear(current,y);await cloud.saveYear(next,0);await cloud.saveConfig({years:[...config.years,{year:y,archived:false}].sort((a,b)=>a.year-b.year)},configVersion);$('year').value=String(y);}catch(e){alert(e.message);}finally{busy=false;render();}};
$('archive').onclick=async()=>{if(busy||!current)return;const want=!current.archived;if(!await confirmBox(want?'封存年度':'解除封存',want?`封存 ${current.year} 年後仍可查詢、匯出與列印，但不可修改或匯入。`:`解除 ${current.year} 年封存並恢復編輯？`))return;busy=true;render();try{const next=structuredClone(current);next.archived=want;await cloud.saveYear(next,yearVersion);const years=config.years.map(x=>x.year===current.year?{...x,archived:want}:x);await cloud.saveConfig({years},configVersion);}catch(e){alert(e.message);}finally{busy=false;render();}};
$('year').onchange=()=>subscribeYear(Number($('year').value));
function subscribeYear(y){if(unsubYear)unsubYear();current=null;yearVersion=0;render();msg('讀取中…');unsubYear=cloud.watchYear(y,data=>{if(!data){msg('找不到年度資料');return;}current=validateYear({year:data.year,archived:data.archived,rows:data.rows});yearVersion=data.version||0;msg('已同步');render();},e=>{msg('讀取失敗');$('auth-message').textContent=e.message;});}
$('login').onclick=()=>cloud?.login().catch(e=>{$('auth-message').textContent=`登入未完成：${e.message}`;});$('logout').onclick=()=>cloud?.logout();
async function seed(){await cloud.saveYear(validateYear(structuredClone(INITIAL_2026)),0);await cloud.saveConfig({years:[{year:2026,archived:false}]},0);}
async function start(){try{cloud=await import('./cloud.js');$('login').disabled=false;cloud.observeAuth(user=>{owner=cloud.isOwner(user);$('account').textContent=user?.email||'';$('logout').hidden=!user;$('login').hidden=!!user;if(unsubCfg)unsubCfg();if(unsubYear)unsubYear();unsubCfg=unsubYear=null;current=null;config=null;render();if(!user){$('auth-message').textContent='請使用管理者 Google 帳號登入。';msg('尚未登入');return;}if(!owner){$('auth-message').textContent='此帳號未獲授權。';msg('未授權');return;}$('auth-message').textContent='正在讀取年度清單…';msg('讀取中…');let seeding=false;unsubCfg=cloud.watchConfig(async data=>{try{if(!data&&!seeding){seeding=true;msg('建立 2026 初始資料…');await seed();return;}if(!data)return;config={years:Array.isArray(data.years)?data.years:[]};configVersion=data.version||0;$('year').innerHTML=config.years.slice().sort((a,b)=>b.year-a.year).map(x=>`<option value="${x.year}">${x.year}${x.archived?'（已封存）':''}</option>`).join('');const target=current?.year&&config.years.some(x=>x.year===current.year)?current.year:Math.max(...config.years.map(x=>x.year));$('year').value=String(target);subscribeYear(target);}catch(e){msg('年度清單異常');$('auth-message').textContent=e.message;}},e=>{msg('連線失敗');$('auth-message').textContent=e.message;});});}catch(e){$('auth-message').textContent='登入服務載入失敗，請確認網路後重新整理。';}}
start();
