const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lines=(...v)=>v.filter(Boolean).map(e).join('<br>');
const cell=(v,attr='')=>`<td ${attr}>${v||'—'}</td>`;
const contacts=p=>lines(p.mobile,p.phone?'/'+p.phone:'');
const name=p=>lines(p.name,p.title);
const specialty=p=>lines(p.name,p.expertise?'/'+p.expertise:'');
const numbered=s=>s.split('\n').filter(Boolean).map(t=>`<div>${e(t)}</div>`).join('');
function ruleBody(s){return s.split('\n').filter(t=>!/^執行方式說明|^越南仁澤廠區/.test(t)).join('\n');}
function taiwan(d){let body='';for(const region of ['北區','中區','南區'])d.rows.filter(r=>r.region===region).forEach((r,i)=>{body+='<tr>'+(i===0?cell(e(region),'rowspan="3"'):'')+cell(e(r.group))+cell(e(r.department))+cell(lines(r.supervisor,r.title))+cell(lines(r.supervisorMobile,r.supervisorPhone))+cell(e(r.leader))+cell(e(r.unit))+cell(e(r.expertise))+cell(lines(r.leaderMobile,r.leaderPhone))+'</tr>';});
return `<h1>台化公司事故調查輪值人員</h1><table class="print-tw"><colgroup>${[6,5,11,12,14,10,17,9,16].map(n=>`<col style="width:${n}%">`).join('')}</colgroup><thead><tr><th rowspan="2">域區</th><th rowspan="2">別組</th><th rowspan="2">輪值事業部</th><th rowspan="2">督導主管</th><th rowspan="2">手機／桌機</th><th colspan="4">組　長（一級主管）</th></tr><tr><th>姓名</th><th>單位</th><th>專長</th><th>手機／桌機</th></tr></thead><tbody>${body}<tr><td colspan="9" class="print-notes">${d.notes.map((n,i)=>`<div>${i+1}. ${e(n)}</div>`).join('')}</td></tr></tbody></table><div class="print-revision">${e(d.revision)}</div>`;}
function china(d){const body=d.overseas.cn.map((t,i)=>{const [s,l,a,b,x]=t.people;return '<tr>'+cell(i+1)+cell(name(s))+cell(contacts(s))+[l,a,b].map(p=>cell(specialty(p))+cell(e(p.unit))+cell(contacts(p))).join('')+cell(e(x.name))+cell(contacts(x))+'</tr>';}).join('');
return `<h1>台化公司大陸廠區重大異常調查輪值人員—${e(d.sourceVersions.cn)}</h1><table class="print-cn"><thead><tr><th rowspan="2">組別／<br>順序</th><th rowspan="2">督導<br>主管</th><th rowspan="2">手機<br>／桌機</th><th colspan="3">組長</th><th colspan="3">組員 1</th><th colspan="3">組員 2</th><th colspan="2">執行幹事</th></tr><tr>${[1,2,3].map(()=>'<th>姓名<br>／專長</th><th>單位</th><th>手機<br>／桌機</th>').join('')}<th>安衛室</th><th>手機<br>／桌機</th></tr></thead><tbody>${body}</tbody></table><h2>執行方式說明：</h2><div class="print-notes">${numbered(ruleBody(d.regionalRules.cn))}</div>`;}
function vietnam(d){const body=d.overseas.vn.map((t,i)=>{const [s,l,x,a,b,c,f]=t.people;let row='<tr>';if(i===0)row+=cell('台灣<br>興業<br>公司','rowspan="6"')+cell('南亞<br>3–4 月<br>及<br>7–8 月','rowspan="3"')+cell('仁澤<br>廠區','rowspan="6"');if(i===3)row+=cell('台化<br>1–2 月<br>及<br>9–10 月','rowspan="3"');row+=cell(e(t.group.split(' ').slice(-2,-1)[0]))+[s,l,x].map(p=>cell(lines(p.name,p.mobile,p.phone))).join('')+cell(e(a.name))+cell(e(a.unit))+cell(contacts(a))+[b,c,f].map(p=>cell(e(p.name))+cell(e(p.unit))+cell(e(p.expertise))+cell(contacts(p))).join('')+'</tr>';return row;}).join('');
return `<h1>越南仁澤廠區各單位負責事故調查之輪值表—（${e(d.sourceVersions.vn)}）</h1><table class="print-vn"><colgroup>${[2,4.4,2.8,2.5,6,6,6,4.2,4.4,6,4.2,4.4,2.7,6,4.2,4.4,2.7,6,4.2,4.4,2.7,6].map(n=>`<col style="width:${n}%">`).join('')}</colgroup><thead><tr><th colspan="2" rowspan="2">公司<br>輪值月份</th><th rowspan="2">廠區</th><th rowspan="2">組別</th><th rowspan="2">督導主管<br>手機／桌機</th><th rowspan="2">組長<br>手機／桌機</th><th rowspan="2">執行幹事<br>安衛室<br>手機／桌機</th><th colspan="3">組員（1）－安衛環</th><th colspan="4">組員（2）－製程</th><th colspan="4">組員（3）－電儀</th><th colspan="4">組員（4）－機械</th></tr><tr><th>姓名</th><th>單位</th><th>手機／桌機</th>${[1,2,3].map(()=>'<th>姓名</th><th>單位</th><th>專長</th><th>手機／桌機</th>').join('')}</tr></thead><tbody>${body}<tr><td colspan="2">河靜鋼公司<br>5–6 月<br>及 11–12 月</td><td colspan="20" class="print-notes">調查小組由河靜鋼公司指派。</td></tr><tr><td colspan="2">說明</td><td colspan="20" class="print-notes">${numbered(ruleBody(d.regionalRules.vn).replace(/\n河靜鋼公司：[\s\S]*$/,''))}</td></tr></tbody></table>`;}
function overview(d){const areas={'tw-north':'台灣北區','tw-central':'台灣中區','tw-south':'台灣南區',cn:'大陸寧波',vn:'越南仁澤'};return `<h1>事故調查出動與輪值紀錄</h1><table><thead><tr><th>地區</th><th>出動組別</th><th>督導主管</th><th>調查日期</th><th>狀態</th><th>當次下次組別</th></tr></thead><tbody>${d.records.map(r=>'<tr>'+[areas[r.area],r.group,r.supervisor,r.date,r.status,r.nextGroup].map(x=>cell(e(x))).join('')+'</tr>').join('')}</tbody></table><h2>補充說明</h2><div class="print-notes">${numbered(d.supplement)}</div>`;}
export function printMarkup(d,kind){const make={tw:taiwan,cn:china,vn:vietnam,overview};return `<article class="paper ${kind==='vn'?'vietnam':''}"><div class="paper-content">${(make[kind]||taiwan)(d)}</div></article>`;}
export function preparePrint(root,html){if(html!==undefined)root.innerHTML=html;root.classList.add('measuring');const p=root.querySelector('.paper'),c=root.querySelector('.paper-content');if(!c){root.classList.remove('measuring');return;}c.style.transform='none';const scale=Math.min(1,p.clientHeight/c.scrollHeight,p.clientWidth/c.scrollWidth);c.style.transform=`scale(${scale})`;root.dataset.scale=String(scale);root.classList.remove('measuring');}
